### ISSUE TITLE
example incorrect

### ISSUE THREAD

**Issue by EveraertJan** [linenoise/asemica#3]
the link https://www.gutenberg.org/cache/epub/2265/pg2265.txt redirects to an overview. It results in the following error:

`Insufficient number of nodes with sufficient exits to perform quality coding using the specified corpus file. Use --force to override (which would likely generate an absurdly long output text).`

could be replaced with https://www.gutenberg.org/cache/epub/2265/pg2265.txt

**Comment by linenoise** [comment]
Fixed, thank you!

https://github.com/linenoise/asemica/commit/19f3b1e9b526f256c3b661e20384ca81223e8d60
