### ISSUE TITLE
State Transition Matrix - "Output Key"

### ISSUE THREAD

**Issue by ghost** [linenoise/asemica#6]
I realized after thinking about the process of `asemica` that there is not an output key like other encryption systems, yet everything is fine when it gets decoded. Most of it makes sense if the user selects a large corpus to get unique tokens. However, how does it know from each transition that one part equals an 'a' and not some other letter or word (for example)?

**Comment by ghost** [comment]
Hello, I just wanted to follow up on this issue. I can tell that it has some correlation with the `bin2dec` and `dec2bin`, but I am still confused about how it works in the actual encoding/decoding process.

P.S.: _I still really appreciate this project because of its uniqueness in concept._

**Comment by linenoise** [comment]
Hi, @ForgivenNin . I don't have the bandwidth to actively support this project right now. I've added you as a collaborator here, so you should be able to make any changes you would like to make. Can you email me at danne@stayskal.com if that doesn't work for you?
